kind: Service
apiVersion: v1
metadata:
  name: node-todo-apps
spec:
  type: NodePort
  selector:
    app: node-todo-apps
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30005

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-todo-apps-deployment
  labels:
    app: node-todo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-todo-apps
  template:
    metadata:
      labels:
        app: node-todo-apps
    spec:
      containers:
      - name: node-todo-apps
        image: foobz/node-todo:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: database
spec:
  selector:
    name: mongodb
    app: database
  ports:
  - port: 27017
    name: db-port
    targetPort: 27017

---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: database
spec:
  containers:
  - name: mongodb
    image: mongo:4.0.2
    ports:
    - containerPort: 27017
